#!/usr/bin/env php
<?php
/**
 * Mince cli runner
 *
 * @package Mince
 */

require_once __DIR__ . '/vendor/autoload.php';

$args = new Qi_Console_ArgV(
    $argv,
    array(
        'quiet|q'   => 'Quiet',
        'verbose|v' => 'Verbose messaging',
        'file|f:'   => 'Mince config file',
    )
);

$terminal = new Qi_Console_Terminal();

$handler = new Qi_Console_ExceptionHandler($terminal, true);

$client = new MinceClient($args, $terminal);

$status = $client->execute($args->file);
exit($status);
